version: '3.8'

services:
  currency-exchange:
    image: jchaconv/currency-exchange-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8000:8000"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411  

  currency-conversion:
    image: jchaconv/currency-conversion-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8100:8100"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411  

  naming-server:
    image: jchaconv/naming-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - currency-network

  zipkin-server:
    image: openzipkin/zipkin:2.23
    mem_limit: 300m
    ports:
      - "9411:9411"
    networks:
      - currency-network      

networks:
  currency-network: